# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rb3XD-mGnbgeVsNy7ImsGt4cOACOFuuT
"""

import pandas as pd
import numpy as np

df2=pd.read_csv('Titanic-Dataset.csv')
df2.head()

Y=df2['Survived']

X= df2.drop(["PassengerId", "Name", "Ticket","Survived","Cabin"], axis=1)
X.head()

"""#Dealing with null values

---


"""

X.isnull().mean()*100

"""#Forward/Backward Fill method



"""

X['Age'] = X['Age'].ffill()   # forward fill

"""#simpleimputer method"""

from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='median')

X[['Age']] = si.fit_transform(X[['Age']])
X

"""#missing values for categorical columns"""

cat_imputer = SimpleImputer(strategy='most_frequent')
X[['Embarked']] = cat_imputer.fit_transform(X[['Embarked']])
X

"""#converting categorical values to numerical values"""

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
X[['Embarked','Sex']] = encoder.fit_transform(X[['Embarked','Sex']])
X

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[
        ('cat', OneHotEncoder(), ['Embarked', 'Sex'])  # list of columns to encode
    ],
    remainder='passthrough')

X = ct.fit_transform(X)
print(X[0])

# Get the column names of the one-hot encoded categorical columns
encoded_cols = ct.named_transformers_['cat'].get_feature_names_out(['Embarked','Sex'])

# Combine with the rest of the columns that were passed through
all_cols = list(encoded_cols) + [col for col in X.columns if col not in ['Embarked','Sex']]

print(all_cols)

"""#Scaling"""

from sklearn.preprocessing import StandardScaler

ss=StandardScaler()
X=ss.fit_transform(X)
X